export const CATEGORIES = [
  'Groceries',
  'Dining',
  'Gas & EV Charging',
  'Transportation',
  'Travel',
  'Shopping',
  'Entertainment',
  'Health & Medical',
  'Fitness',
  'Home & Utilities',
  'Insurance',
  'Subscriptions',
  'Education',
  'Donations & Charity',
  'Government & Fees',
  'Telecom',
  'Personal Care',
  'Pets',
  'Gifts',
  'Other',
  'Miscellaneous',
  'Transfer',
  'Credit Card Payment',
  'Refunds & Credits',
  'Needs Review',
] as const

export type Category = (typeof CATEGORIES)[number]

export const CATEGORY_ICONS: Record<string, string> = {
  'Groceries': '🛒',
  'Dining': '🍽️',
  'Gas & EV Charging': '⚡',
  'Transportation': '🚗',
  'Travel': '✈️',
  'Shopping': '🛍️',
  'Entertainment': '🎬',
  'Health & Medical': '🏥',
  'Fitness': '💪',
  'Home & Utilities': '🏠',
  'Insurance': '🛡️',
  'Subscriptions': '🔄',
  'Education': '📚',
  'Donations & Charity': '🤲',
  'Government & Fees': '🏛️',
  'Telecom': '📱',
  'Personal Care': '💆',
  'Pets': '🐾',
  'Gifts': '🎁',
  'Other': '📦',
  'Miscellaneous': '📦',
  'Transfer': '↔️',
  'Credit Card Payment': '💳',
  'Refunds & Credits': '↩️',
  'Needs Review': '⚠️',
}

export const CATEGORY_COLORS: Record<string, string> = {
  'Groceries':          '#22c55e',
  'Dining':             '#f97316',
  'Gas & EV Charging':  '#eab308',
  'Transportation':     '#06b6d4',
  'Travel':             '#8b5cf6',
  'Shopping':           '#ec4899',
  'Entertainment':      '#f43f5e',
  'Health & Medical':   '#14b8a6',
  'Fitness':            '#84cc16',
  'Home & Utilities':   '#64748b',
  'Insurance':          '#0ea5e9',
  'Subscriptions':      '#a78bfa',
  'Education':          '#3b82f6',
  'Donations & Charity':'#10b981',
  'Government & Fees':  '#6b7280',
  'Telecom':            '#0891b2',
  'Personal Care':      '#d946ef',
  'Pets':               '#78716c',
  'Gifts':              '#fb923c',
  'Other':              '#94a3b8',
  'Miscellaneous':      '#94a3b8',
  'Transfer':           '#0ea5e9',
  'Credit Card Payment':'#64748b',
  'Refunds & Credits':  '#10b981',
  'Needs Review':       '#f59e0b',
}
